- type: startingGear
  id: DeathSquadBaseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    suitstorage: OxygenTankFilled
    eyes: ClothingEyesGlassesDeathsquad
    # neck: ExecutiveIDCard # Arcane-Edit
    gloves: ClothingHandsGlovesDeathsquadUnremovable
    outerClothing: ClothingOuterHardsuitDeathsquadUnremovable
    shoes: ClothingShoesBootsMagDeathsquadOn
    head: ClothingHeadHelmetHardsuitDeathsquad
    id: DeathsquadPDA
    belt: ClothingBeltDeathsquadWebbing
